### ISSUE TITLE
Word templates no longer maintained

### ISSUE THREAD

**Issue by shardulc** [glederrey/EPFL_thesis_template#10]
Hi, writing on behalf of PolyDoc. We received an email from the doctoral school informing us that the MS Word templates that used to be available on [their website](https://www.epfl.ch/education/phd/regulations/internal-regulations/edoc-faq-end-of-thesis/) were taken down because they were severely out of date. But they noticed that the README for this repo still mentioned them and asked for that sentence to be removed too. Thanks for your attention!

**Comment by glederrey** [comment]
Hi,

I'll remove the link in the README.
