### ISSUE TITLE
Issue using the template in overleaf

### ISSUE THREAD

**Issue by rabeehk** [glederrey/EPFL_thesis_template#2]
Hi
many thanks for sharing the template, I am getting this error, when compiling the files on overleaf, I appreciate any idea on this.
thanks
Best
Rabeeh 

Emergency stop.

<*> settings_epfl_template.tex
                              
*** (job aborted, no legal \end found)

 
Here is how much of TeX's memory you used:
 27589 strings out of 478542
 491822 string characters out of 5850413
 931709 words of memory out of 5000000
 45076 multiletter control sequences out of 15000+600000
 408721 words of font info for 30 fonts, out of 8000000 for 9000
 1141 hyphenation exceptions out of 8191
 84i,0n,83p,434b,424s stack positions out of 5000i,500n,10000p,200000b,80000s
!  ==> Fatal error occurred, no output PDF file produced!

**Comment by glederrey** [comment]
Hi, 

You simply have to select the Main document in the settings in overleaf. It's on the top left corner. Then, you'll have a drop down menu named Main document. 

Let me know if it fixed the issue. =)

**Comment by rabeehk** [comment]
thanks a lot, I was compiling the main document in fact, but the issue resolved after setting main document in setting as you mentioned, many thanks
