### ISSUE TITLE
Bibliography in Contents page added multiple times

### ISSUE THREAD

**Issue by nkv1995** [glederrey/EPFL_thesis_template#5]
https://github.com/glederrey/EPFL_thesis_template/blob/e9c3a490d00a6166430328c55abd49ecceba438a/tail/biblio.tex#L6

Both in Line 3 and 6 of bibilo.tex, Bibliography is added to the contents. As a result, you can see Bibliography chapter being generated two times on the contents page. Kindly correct this.  I'm not sure if this is intended, but many official theses that I went through have this.

<img width="1332" alt="Screenshot 2022-04-06 at 12 03 43" src="https://user-images.githubusercontent.com/81468432/161951161-3b98161e-e170-4234-8767-85b511a9d0cc.png">

**Comment by glederrey** [comment]
Hi,

There's definitely an issue here. I will fix that. Thanks for pointing that out.

**Comment by glederrey** [comment]
It's fixed. Thanks again
