### ISSUE TITLE
Mabye a unit error?

### ISSUE THREAD

**Issue by LMSC-NTappy** [glederrey/EPFL_thesis_template#6]
First, thank you so much for all your work creating this beautiful template!

Current version issues a small warning and I think there just might be a typo in the epfl settings file.

Head height is set to 14 pt (which is less than the allowed min apparently) and I think you meant 14 mm as seen from the comment in the previous line

https://github.com/glederrey/EPFL_thesis_template/blob/897e07d3d4747ae0a377b258b963517addc284f2/head/settings_epfl_template.tex#L54-L55

Thought I might share, also to take the opportunity of saying thank you :)

Love from a former classmate <3 

N T

**Comment by glederrey** [comment]
Hi Nicolas,

Thanks a lot. I didn't even see this warning. 

Would it be possible for you to do a PR? That way, you'll be properly thanked. If you don't care, I can make the change (and just check everything's fine). 

Thanks a lot =) (And I'm just maintaining the template. I did not create it. And I didn't add anything on it. =P)

**Comment by LMSC-NTappy** [comment]
Hello

Sure I will do the PR towards the end of the week! I don't mind if you do it but I don't mind being thanked either :)

**Comment by LMSC-NTappy** [comment]
Here it is. I let you to it
